### ISSUE TITLE
Merge p2p_send with p2p_query

### ISSUE THREAD

**Issue by KenBirman** [Derecho-Project/derecho-unified#117]
We merged ordered_send and ordered_query a few weeks ago.  At this point we should probably do the same for p2p_send and p2p_query.

**Comment by sagarjha** [comment]
Actually, this is high priority. `p2p_send` can get stuck because it expects that we are calling a function that does not return anything. When we have merged `p2p_send` and `p2p_query`, then we will automatically factor in void and non-void returning functions.

**Comment by sagarjha** [comment]
Fixed, but a lot of simplifying refactoring is needed.
This required a lot of changes in the P2P RDMA layer. The P2P layer previously assumed that `p2p_send` do not generate a reply, while `p2p_query` does. It matched each `p2p_query` with a reply in order to do its ring buffer management.
Now, there's only `p2p_send`. What this means is that some will generate replies, some will not. To take care of this, I am currently sending a dummy reply to reduce this to the case where every request generates a reply.
The P2P layer still assumes that there are two request types, one of which is now never used. Therefore, I will refactor it to forget that.

**Comment by KenBirman** [comment]
This hidden reply will be useful: it lets us support status tracking, which would be an additional way to “align” p2p_send with ordered_send, making the entire API kind of similar to asynchronous I/O in Linux or Windows.
