### ISSUE TITLE
Add a compile-time tag to indicate replicated objects with Persistent<T> fields

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho-unified#31]
There are several places in Derecho where it would be very helpful to know whether a user-defined Replicated Object (the `T` in Replicated<T>) has defined any Persistent fields (using the Persistent<T> template). Unfortunately, C++ doesn't have compile-time reflection that would allow us to determine whether a given class has any fields of a particular type. Rather than deal with the increasing code complexity of trying to guess whether an object has Persistent fields, or pessimistically assume all objects are persistent, we decided to add a marker interface that user-defined Replicated Objects must inherit to indicate that their object has Persistent fields.

**Comment by KenBirman** [comment]
Completely agree about that!

Sent from my iPhone

On Jun 11, 2018, at 12:22 PM, Matthew Milano <notifications@github.com<mailto:notifications@github.com>> wrote:


The motivation behind this marker interface isn't quite because we simply can't deal with the uncertainty; right now we actually do assume all Replicated have persistent fields. It's more to fight code complexity and avoid the windy runtime pathways that have resulted from that assumption. It's much nicer for us to partition away the persistence code into separate methods overloaded on this marker interface and keep the normal replicated pathways devoted to just replicated's concerns.

There might be an efficiency argument to it as well, but I'm not quite sold on that one; the codepaths for handling persistence will be relatively short in the case that persistence is actually unused. Still, the less code we need to run the better!
