### ISSUE TITLE
Const qualifications and cooked expressiveness

### ISSUE THREAD

**Issue by mpmilano** [Derecho-Project/derecho-unified#34]
The register_rpc_functions class makes awkward assumptions about what sort of methods we will register for RPC in the first place.  In particular, they cannot be reference-returning or const-qualified.  These restrictions will bite us.

**Comment by etremel** [comment]
By "register_rpc_functions class," do you mean the RemoteInvocableClass class and its associated tag() and bind_to_instance() function templates? register_rpc_functions is the name of a header file that contains a bunch of auto-generated macros, not a class.

Assuming I guessed right about the code you're referring to, what is the right solution here? Can we require that registered RPC functions are not reference-returning or const-qualified by putting some restrictions on the template parameters for `partial_wrapped`, `wrapped`, `tag()`, or `bind_to_instance()`? As far as I know, there's nothing in the C++ template system that allows you to partially restrict a template type to only match non-const or non-reference types. But then again, you're the expert on the C++ type system, so maybe there is a way to do that.

**Comment by mpmilano** [comment]
The fundamental problem is that partial_wrapped explicitly has its function as a `Ret (Class::*)(Arguments...);`, which doesn't allow `const`-qualified functions.  It should instead be either a `Ret (Class::*)(Arguments...);` or a `Ret (Class::*)(Arguments...) const;`.  That needs to change, and everything that interacts with it (creates it, consumes it, passes it along) needs to be checked and changed if necessary.

**Comment by etremel** [comment]
Oh, so you're saying that the assumption that the wrapped function is not const-qualified is an unnecessary restriction and should be lifted by providing both const and non-const versions of the `tag()` function. I can do that. On the other hand, was I correct in guessing that the restriction against reference-returning functions is intentional and just needs to be enforced? An RPC-invoked function really shouldn't return a reference, because the result will be copied across the network, and a reference or pointer to local memory on the executing node will become invalid.

**Comment by mpmilano** [comment]
I'm not sure about that one; these functions can technically still be called locally too.  We definitely would copy the return value across the network in either case.  Either way, we should give a much better error message for things like this.  We should also enforce that the arguments to RPC-able functions are taken by reference.  Putting a `static_assert` to test `is_lvalue_reference` (or `!is_lvalue_reference`) in the right places is probably the right call.
