### ISSUE TITLE
Derecho with SoftRoCE

### ISSUE THREAD

**Issue by lapd-viosoft** [Derecho-Project/derecho-unified#52]
Hi,
I'm trying derecho_bw_test Derecho with SoftRoCE.
This is the soft device I found
```sh
  Name  Link  Driver      Speed  NMTU  IPv4_addr  RDEV  RMTU          
  ens3  yes   virtio_net                                              
  ens6  yes   i40e                                rxe0  1024  (3)
```

I did update rdma.cfg file (domain = rxe0)  then try to run the app, but I got the following error
```sh
Please enter IP Address for node 0: 192.168.6.20
Please enter IP Address for node 1: 192.168.6.21
/home/administrator/derecho-unified/rdmc/lf_helper.cpp:688,ret=-61,fi_getinfo() failed
[139686371360960] shutdown_polling_thread() begins.
[139686371360960] done with shutdown_polling_thread().
```
It seems the domain = rxe0 (in rdma.cfg) is not correct.
Could you please tell me what is the expected value to for "domain" in the rdma.cfg file?
Thank you!

**Comment by KenBirman** [comment]
We were not able to port to SoftRoCE due to many bugs in their implementation.  Instead, use LibFabrics in its TCP mode.

On Sep 28, 2018, at 7:51 AM, Lap Ngo <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I'm trying derecho_bw_test Derecho with SoftRoCE.
This is the soft device I found

  Name  Link  Driver      Speed  NMTU  IPv4_addr  RDEV  RMTU
  ens3  yes   virtio_net
  ens6  yes   i40e                                rxe0  1024  (3)

I did update rdma.cfg file (domain = rxe0) then try to run the app, but I got the following error

Please enter IP Address for node 0: 192.168.6.20
Please enter IP Address for node 1: 192.168.6.21
/home/administrator/derecho-unified/rdmc/lf_helper.cpp:688,ret=-61,fi_getinfo() failed
[139686371360960] shutdown_polling_thread() begins.
[139686371360960] done with shutdown_polling_thread().

It seems the domain = rxe0 (in rdma.cfg) is not correct.
Could you please tell me what is the expected value to for "domain" in the rdma.cfg file?
Thank you!

**Comment by lapd-viosoft** [comment]
Thank KenBirman,
Do you mean that we can use Derecho with LibFabrics in its TCP mode with Intel X710 NIC?

**Comment by lapd-viosoft** [comment]
I got it, "libfabric can work on TCP/IP network without special RDMA hardware" 
Thank you!
