### ISSUE TITLE
Work with libfabric community to decide a solution for FI_SELECTIVE_COMPLETION

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho-unified#57]
The latest libfabric verbs implementation decide to turn on `sq_sig_all` on calling `ibv_create_qp()`. This will stop FI_SELECTIVE_COMPLETION from working: all RDMA write will receive a completion entry no matter if the FI_COMPLETION flag is set or not.

@dmitrygladkov insists this design but let libfabric keeps only demanded on in the completion queue. see [this pull request](https://github.com/ofiwg/libfabric/pull/4475).

I posted [this solution](https://github.com/ofiwg/libfabric/pull/4474) because I believe the performance is going to be better.

I am discussing with @dmitrygladkov.

**Comment by shefty** [comment]
Verbs devices require the periodic generation of a completion, even if the application never wants one, or the send queue will block.  For example, if the send queue size is 512, then there MUST be a completion generated at least once for every 512 transfers. The completion indicates that all previously posted operations have completed, which frees the send queue slots for re-use.  Without a completion being generated, the verbs software has no way of knowing when it is safe to re-use a send queue slot for a new operation.

Because libfabric doesn't have this requirement, it needs to ensure that a completion is generated for apps that submit more "no completion requests" than allowed by the underlying device.  This results in a significant amount of overhead, which was removed from the upstream libfabric code.  The commit that removed this support is here:

https://github.com/ofiwg/libfabric/commit/00c1bb1a48a48a2d92d3f95517e4f0b53b2cbff1

To re-enable the ability to completely disable completion generation requires re-implementing something similar to what was removed in the above patch.  Basically, it's non-trivial, and most application developers aren't even aware of this limitation.

**Comment by sagarjha** [comment]
Yes, we have to periodically clear outstanding requests in the NIC. We turn the completion off when initializing the queue pair (`qp_init_attr.sq_sig_all = 0;`) and selectively post operations that enable completions every few milliseconds. A successful completion for an RDMA operation on a queue pair clears all the outstanding requests on that queue pair.

**Comment by songweijia** [comment]
I think we can take libfabric fix [#4475](https://github.com/ofiwg/libfabric/pull/4475) for now. If we see significant overhead, we can re-consider a sophisticated solution later.

**Comment by songweijia** [comment]
Upgrade to the latest libfabric with the fix. See commit f3db843807b6d2df4ab55933eedcd20e92291fb4.
