### ISSUE TITLE
RPC calls do not work across platforms

### ISSUE THREAD

**Issue by sagarjha** [Derecho-Project/derecho-unified#61]
Even though raw messages seem to work across platforms (for this issue, consider a network of 2 nodes, my local laptop and a fractus node), RPC calls are broken. I tested `derecho_caller_test.cpp` and verified that the nodes segfault. This is probably because of some hard constraints around serialization of type_indexes. @etremel is going to say more about this.
It is worthwhile to note that my laptop has Ubuntu 18.04 with `g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0` and Fractus has 16.04 with `g++ 7.3.0 (Ubuntu 7.3.0-21ubuntu1~16.04) `. But, even Edward noticed this problem when he was testing on his local desktop and a Fractus node. He has Ubuntu 16.04 on his local machine and the same g++ version as on Fractus.
Years ago, we always wanted the same "binary" to be shipped to all the nodes. That's not realistic across platforms.

**Comment by KenBirman** [comment]
Perhaps they do not use the same endian representation or cache-line size.  Our form of RDMA assumes that the Derecho programs run on compatible hardware.

**Comment by etremel** [comment]
The specific problem here seems to be that the std::type_index component of the RPC `Opcode` is not interpreted correctly on the receiving side, leading it to fail when it attempts to look up a RemoteInvoker by comparing Opcodes. It's unsurprising that any minor difference in platforms (compiler, OS, environment) would cause a std::type_index to be deserialized incorrectly, because all we do to serialize and deserialize std::type_indexes is copy the raw bytes to the message buffer, then reinterpret those bytes as a std::type_index. Since std::type_index is an opaque internal type that contains pointers, this is inherently unsafe.

A better way to identify the Replicated Object class associated with a function Opcode would be to use the object's (mangled) typename, as returned by std::type_index::name(), rather than the entire std::type_index structure, since typenames are easily-serialized strings and not likely to change significantly between different minor versions of the compiler.

**Comment by KenBirman** [comment]
In Vsync,  this sometimes arose because of separate compilations.  I ended up mashing all the type signatures into a single 33-bit hash, and rejecting a join request if it didn’t match the one in use by the leader.

**Comment by mpmilano** [comment]
I think I might have mentioned this before, but type_index really isn't supposed to be serialized. We're getting away with it so long as the platforms are identical, but it's very very implementation-specific what happens when they're not. In particular, I'm worried that different versions of libstdc++ will treat these things differently.

**Comment by KenBirman** [comment]
When I read “isn’t supposed to be” I feel like I’m hearing about a guaranteed future bug.  Edward, why do you serialize this?  Matt, what should we be doing in the case Edward is looking at.

In Vsync, I actually used a map from type name to type.  C# types have string names, but in C# it works just as well to invent names, like an enumeration: DERECHO_INT_32, DERECHO_INT_64, … with small integer numerical values.  Easy to transmit, serialize correctly, and then you recover the types from the table…

In C++ we can get the same behavior with a switch statement, one case per type.  But we would need to know the set of types ahead of time, when we compile

**Comment by mpmilano** [comment]
We should be able to generate a unique integer per type introduced in the group constructor via this code snippet: 

`template <std::size_t init, typename T, typename T2, typename... seq>
constexpr std::size_t index_translate_f() {
  if constexpr (std::is_same<T, T2>::value)
    return init;
  else
    return index_translate_f<init + 1, T, seq...>();
}`

`template <typename T, typename... seq>
constexpr inline std::size_t
index_translate = index_translate_f<0, T, seq...>();`

This takes a type and a list of types, and returns an integer indicating which index into the list matched the requested type.  

This assumes that the point at which we'd need a type index is somewhere where the list of types (from group) is in scope.  If there's no point like that, we'd need to either use virtual functions or store a closure which calls the indexing function.

**Comment by mpmilano** [comment]
There will be a related bug hiding in opcode generation for individual method calls.  I'm pretty sure that right now this relies on static initialization order, which is something that's not influenced by the libraries you link and thus is consistent across runs of the same binary.  But that's not guaranteed by the standard, so we should stop relying on it.  We can replace this opcode generation with one in which the opcode is a pair of the containing type "index" (generated as suggested in my earlier comment) and the position in the list of methods the class is registering.  i.e. the opcode (3,4) refers to the 3rd type (as passed into the group constructor), 4th method (in the order registered for that type).

**Comment by etremel** [comment]
To answer Ken's question, I wasn't the one who chose to serialize std::type_index when serializing Opcodes for RPC function invocations; I didn't write that code, so I don't know who made that decision. Ever since I noticed that we were serializing std::type_index as part of the Opcode in an RPC header I have thought that this was guaranteed to break at some point and wanted to replace it with something more portable, but since it was (at the time) working just fine I didn't have the time to fix it.

To answer Matthew's question, the list-of-replicated-types template parameter is not available anywhere outside the Group class, so it wouldn't be available in the Replicated and RPCManager classes, which is where Opcodes are sent and received. This is why we've been relying on std::type_index in the RPC subsystem to identify user-defined replicated objects: it's a unique identifier based on a typename that doesn't require the actual typename to be carried around in a template in order to use it. However, it looks like Replicated objects don't actually need to construct Opcodes on each RPC send, because once the Opcode for a function is constructed in the RemoteInvocable/RemoteInvoker constructors, it is saved as a class member and reused on every RPC message send. Furthermore, the RemoteInvocable constructors do get the type of the replicated class they are generating Opcodes for as a template parameter; they currently use this to construct the std::type_index that is saved in the Opcode for each RemoteInvocable. So if we can come up with a way to translate this template parameter into a unique integer at the time RemoteInvocable/RemoteInvoker is constructed, we won't actually need access to the type-to-integer function (or any templates) at the time RPC functions are called and handled.

Finally, when you say "opcode generation for individual method calls," what do you mean by "opcode"? I've been using Opcode to mean the struct that contains the set (type_index, subgroup_id, function_id, is_reply), but only one part of this (the function ID) is different per method. And as far as I can tell, function IDs, which are uint64's, are generated by the user when he/she registers RPC functions in the required register_functions() method - each function gets a "tag" template parameter, which is passed through to the RemoteInvocable constructor to be used as the FunctionTag element of the Opcode. So how is this relying on static initialization order?

**Comment by KenBirman** [comment]
Edward and I just discussed this and arrived at an elegant solution.  Anyone using RPC is specifying the proper replicated<T> type.  So, we can use the macro trick to transform the typename X into the string X.  Having done so, we can do a constexpr hash on that string, thus obtaining a type-id that is independent of compilation order and that should be free of collisions.  Using this as the new definition of typeid would seemingly eliminate the bug!

**Comment by mpmilano** [comment]
Yes that would work. Though I thought the macro only contained the name of the method, with only the invocation still via a replicated<T>. Though I suppose we could extend the macro to just capture both. 

In response to my bug-waiting-to-happen warning, it looks like someone fixed that months ago. So all told this is going to end up just fine

**Comment by KenBirman** [comment]
Well, the RPC invocation uses the type, so the type is available in the RPC code.  The template defining replicated<T> just needs to have a const property, at which point Edward would have the needed identifier.  And since we would use string hashing, this will be constant across platforms and compilers as long as the string hash is computed using the same constant expression...

**Comment by mpmilano** [comment]
As it turns out, template-expansion happens after macro-expansion; so if you're trying to capture the type-name of a template argument with a macro, you'll just get the name of the template parameter instead.  Right now we don't have a way of capturing the actual name of a type with just templates; the way the standard defines (puzzlingly) isn't constexpr-safe, and so can't run at compile-time.  I just talked this over with Edward, and we came up with a different solution based on my original suggestion: while we're still in the group constructor, we compute the index of our replicated type into the list of type parameters for the group.  We pass that along into the Replicated constructor, and use it in place of type_index.

**Comment by sagarjha** [comment]
I tested `derecho_caller_test` with two Fractus nodes and my laptop. All have Ubuntu 16.04. And it works!
I tested the same application with two Fractus nodes running Ubuntu 16.04 and one Fractus node running Ubuntu 18.04. And it works!
Then I tested on one node on Fractus running Ubuntu 16.04, one node on Fractus running Ubuntu 18.04 and one node on **Cloudlab** running Ubuntu 16.04 on an **ARM** machine. Some things work and some things FAIL. If I use the three nodes in order (node ids 0, 1 and 2 resp.) then it the first two nodes are able to talk to each other and run RPC functions. The third node throws an error `failed to connect remote. nRead=-259.` and all nodes exit as a result. When I change the order of the nodes so that node id 0 is still Fractus Ubuntu 16.04, node id 1 changes to the Cloudlab server and node id 2 is the Fractus 18.04 machine, then it again works!

**Comment by KenBirman** [comment]
When we use scatter gather, I bet there would be other things that would still fail.  Think of ARM sending to x86: unless Matt does some form of padding in his marshaller, with scatter gather his code  could easily generate a binary layout that the receiver can’t use for an upcall with arguments passed by reference.  Yet padding when not needed could be costly (it needs an extra verb).

Sent from my iPhone

On Nov 27, 2018, at 4:20 PM, Sagar Jha <notifications@github.com<mailto:notifications@github.com>> wrote:


I tested derecho_caller_test with two Fractus nodes and my laptop. All have Ubuntu 16.04. And it works!
I tested the same application with two Fractus nodes running Ubuntu 16.04 and one Fractus node running Ubuntu 18.04. And it works!
Then I tested on one node on Fractus running Ubuntu 16.04, one node on Fractus running Ubuntu 18.04 and one node on Cloudlab running Ubuntu 16.04 on an ARM machine. Some things work and some things FAIL. If I use the three nodes in order (node ids 0, 1 and 2 resp.) then it the first two nodes are able to talk to each other and run RPC functions. The third node throws an error failed to connect remote. nRead=-259. and all nodes exit as a result. When I change the order of the nodes so that node id 0 is still Fractus Ubuntu 16.04, node id 1 changes to the Cloudlab server and node id 2 is the Fractus 18.04 machine, then it again works!
