### ISSUE TITLE
TCP connections are never removed from RDMC and SST

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho-unified#64]
Both RDMC and SST have internal, global pools of TCP connections to every node in the group. These are separate from the Derecho TCP connections pool that was formerly used to send and receive P2P messages (before Sagar implemented P2P over RDMA). When a new node is added to a Derecho group, the view-change logic calls `rdma::impl::lf_add_connection` and `sst::add_node` to add a TCP connection to this node to those internal TCP pools, but when a node leaves a Derecho group there is no corresponding logic that removes its TCP connection from the pools.

**Comment by sagarjha** [comment]
Specifically, this bug prevented a node joining the group with the same id because existing nodes tried to use the same socket for the new node which had become defunct. We verified that after the bug fix, the new node can join if it is not in the members list (and not in the departed list either).
We are yet to handle the case when a node fails, the group wedges because it is waiting for more nodes and the same node tries to rejoin with the same id. Then the joining node is also present in the departed list. This is a problem as it stands right now.
