### ISSUE TITLE
P2P and Ordered sends do not need to track replies

### ISSUE THREAD

**Issue by sagarjha** [Derecho-Project/derecho-unified#65]
This continues the discussion in #63. Tracking replies through `fulfill_map`, `fulfilledList` and `toFulfillQueue` should only be done when we are querying (P2P or Ordered), not when sending. This was fixed for P2P sends in commit d9e682d1e8531d44fd9c739cdd683de207db5b65. We need to do the same for Ordered sends.

**Comment by etremel** [comment]
I remember the discussion about wanting to track receipt of void RPC functions (ordered sends), but in fact that isn't possible with the current API design because the `ordered_send` and `p2p_send` functions return void - they discard the PendingResults object that RemoteInvoker::send() returns. We have plans to consolidate the `ordered_send` and `ordered_query` functions (see issue #4), which would give users the ability to look at the PendingResults for a void function, but at the moment there is no way to use them. Also, although there is a specialization `PendingResults<void>` (which I think is what you're talking about when you say "a specialization of the reply_map for void-returning replies"), that class currently has no functionality: calling fulfill_map() on it does nothing because it does not actually track replies.

Meanwhile, when you say that fulfillment maps exist and we shouldn't eagerly discard them, are you talking about the else clause in line 124 of rpc_manager.cpp (at d9e682d), which pops and discards PendingResults objects from toFulfillQueue for void functions? The reason why I wrote that clause was to fix bugs caused by useless PendingResults<void> objects: they were added to toFulfillQueue by finish_rpc_send(), but then rpc_message_handler never fulfilled them because it was looking for RPC messages that were query invocations, and this made the toFulfillQueue get out of sync with the incoming self-receives of query invocations. Since PendingResults<void> has no functionality, it must either be discarded from toFulfillQueue at the same rate it is inserted, or never inserted at all. 

What we're proposing to do here is simply never insert a PendingResults<void> into toFulfillQueue, by passing an `is_query` parameter to finish_rpc_send(), and then eliminate the else clause that discards the PendingResults<void>s.
