### ISSUE TITLE
More settings need to go to the configuration file

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho-unified#66]
We should move the following setting to the configuration file to make a Derecho application more concise:

1) node id, local address
When a node recovers from a failure, it may restart with a different id. Therefore the node may choose to start with another id. 

2) maximum message size, maximum SST message size, block_size, window_size.

Going to do this after #60

**Comment by sagarjha** [comment]
maximum message size and maximum SST message size and block size and window size will remain in the test files. They will not move to the config files.

**Comment by songweijia** [comment]
@sagarjha , the configuration can be overridden in the test: The default constructor of `DerechoParams` pick settings from configuration. But we can still have them defined explicitly in the test in case of performance evaluation with varying configurations.

**Comment by sagarjha** [comment]
We do provide a default config file, Ken. We probably also have defaults. Weijia might know.
Also, if you want to be blind to the implementation details, you really are asking for zero performance. If the message size is 1 GB and you are sending 1 byte messages, then you are wasting a lot of space. If you have a message size of 10 KB and try to send larger, your program will throw up.

**Comment by KenBirman** [comment]
I’m ok with there being optional arguments to Derecho::start for these purposes, if properly documented, but I don’t like the variables being global that must be initialized by hand this way.  And they really do need sensible defaults, even so.

**Comment by sagarjha** [comment]
Why do you think the variables are global? They are passed to Derecho at group construction time as DerechoParams. Please look at a test file.

**Comment by KenBirman** [comment]
I see, but to me this makes no real difference – those could be allowed to default if not specified.  They can be the last arguments to the constructor, or you can just specify multiple constructors with various mixes of optional parameters, in the usual way.  The defaults could match what we use in the TOCS paper.   Documentation for the group constructor should state that the defaults will be used if not overridden and indicate what those values would be, or what environment parameter is used to import them, if you prefer to have the configuration manager handle that aspect.

In effect we should move away from assuming that the Derecho user is able to specify sensible values, and towards a mode in which we use sensible defaults but make it clear that these are parameters the user actually should override if aware of reasons to do so.

Additionally, many applications will have “mostly” subgroups using small messages, but “some” subgroups carrying very large objects.  Thus, these estimated size numbers need to be per-subgroup, not for the group as a whole, covering all subgroups.  This is because most objects are smallish in real systems, but images or videos or parameter vectors for machine learning systems are large (gigabytes).

In a test where the “point” is to evaluate with special values, or to accept them as arguments, there should be (1) a comment indicating that this is why they are being set this way, and (2) for the latter, logic to extract them from an argument.  Or alternatively, external logic to pass in unusual values by overriding environment variables that would either have had no value at all, or held some default value.

**Comment by songweijia** [comment]
Options now moved to both configuration file and command line argument. See conf/derecho-default.cfg.
