### ISSUE TITLE
Help Wanted for Derecho SST Routing example

### ISSUE THREAD

**Issue by nhannx-viosoft** [Derecho-Project/derecho-unified#67]
Hi, I'm learning SST via your samples. When I try to run SST routing sample (router_experiment.cpp), it requires 2 configuration files and I have no idea for these two.
Could you please to show me more about participating nodes and initial router state config files?

**Comment by sagarjha** [comment]
Hi Nguyen,
Sorry, the routing experiment was written 2-3 years ago. The config files it takes contains input about the number of nodes and their addresses. But, the test hasn't been maintained since. It most likely does not even compile.
I will suggest you to try out other SST examples. Here is a short introduction of the samples we do support:
1. `sst_test.cpp`: Creates an SST with a single integer a. The participating nodes receive their IDs (unique integers), total number of nodes and the IP address of each node. They then set their own value of a and print the entire table before exiting.
2. `simple_predicate.cpp`: Shows an example of a predicate (event handler) on the SST.
3. `count_write.cpp`: Runs a distributed counting test. The SST has a single counter. Every node starts with their counter value 0. Everyone then increments it by 1. When they see that everyone has increment it to 1, they increment it again. And so on. The test measures how much time it takes for the counter value to reach a million.
4. `multicast_throughput.cpp`: Shows a sophisticated example of how to use the SST multicast feature. Every node maintains a ring of buffers in the SST and have predicates that detect if a new messages from any other node is available. The experiment sends a million 1-byte messages from every node to all the members and measures the throughput. Both the number of messages and the message size is defined in the test itself. You can change them both.
There may be further issues running any of the tests. In that case, please reply here for assistance.
