### ISSUE TITLE
Derecho's default membership allocation is broken!

### ISSUE THREAD

**Issue by sagarjha** [Derecho-Project/derecho-unified#71]
Users, for their subgroup membership, can provide Derecho with membership allocation function. But, to ease their task, we provide default allocation functions that capture common patterns they are likely to use. For example, they can tell us that they need 2 subgroups with 2 and 3 shards each and we will pick the members for the shards that tries to keep the memberships stable across view changes (failures and joins). One thing to point out about our membership allocation (default or user-provided) is that all nodes run the functions in parallel. Thus, it is our requirement that the membership of the subgroups they arrive at, separately, must be the same across all the nodes.
Edward ran into a problem with his total restart case when using the default membership allocation. The group is provisioned when there are at least 6 members. He starts the first 5 members first after which the leader is waiting for one more node. Before starting the 6th member, however, he fails one of the existing nodes (3rd node). Then, after starting the 6th member, he adds another node to make the total number of nodes back to 6. This leads the leader to conclude that the group is provisioned after which all nodes proceed to establish network connections. At this point, an all-member barrier in a particular subgroup hangs.
The problem is that our default membership function lacks enough context at the new joining node to arrive at the same membership as for the existing nodes. This is not particular to the restart case Edward is working on; this can happen whenever a node leaves a view and a new node joins subsequently. In particular, the new joining node needs to know the previous membership of the group. This will help it determine, for example, that it is going to fill up for an now-extinct node that belonged to a subgroup.
We had a discussion 1-2 years ago, probably before any default allocation mechanism existed, on whether we should have the leader send the membership to all the nodes, or have everyone compute it separately. We settled on the later for efficiency purposes. Now, it seems that either we send the membership computed at the leader to all the members, or send enough state across from the leader so that everyone has the right context to arrive at the "correct" membership. On closer inspection, the first solution is not sufficient, as on a leader failure, whatever state that was necessary to form the correct membership is lost. Thus, it is in fact, a state machine replication problem.
I am suggesting something much more general to fix this. It requires some amount of work. Before I discuss that, let me clarify that Edward is not stalled on his development. For now, he is manually specifying a membership that does not suffer from a lack of context at new nodes and proceeding to debug the rest of his implementation for total failure restart.
We have always wanted some top-level group functionality on top of the subgroups. I suggest we create an internal top-level replicated object, just as the users construct their own subgroup objects. The view will be part of this object, as will be the state required by the membership allocation system. We can even make this extendable so that the user can add functionality they deem important for the top-level group. The nice thing about this, as Edward pointed out, is that the membership functions are simply the functions of this object and are registered by the user in advance. Then all members are required to provide the same functions as they do for the subgroups. In particular, for the current default allocation scheme, the previous assignment can be a data member of this object.
Finally, when a new node joins, it receives the entire group state object from the leader, instead of just the view. It can then separately run the membership allocation function to determine the memberships.

**Comment by KenBirman** [comment]
This note is extremely interesting.  I like the proposed extension, although I feel as if Edward’s current solution really does run Paxos for the reboot step and as such, is correct (at least if fully implemented – if he implements a short-cut, like a 2-phase commit or a 3-phase commit that doesn’t iterate in each of the two stages, there could be cases where it would malfunction --- very unlikely cases, though, and perhaps far too unlikely to be real risks).

A further benefit to your proposal, not mentioned in your email, is that if we do this, we can also start to include additional information along with the group state object.  I’ve wanted to see us move towards top level membership extended with some form of user-specified objects (one per subgroup) that could be type-specific configuration data or parameterization.  The view isn’t extensible in a natural way for this purpose because the view doesn’t know the subgroup types.  But the top-level group state does know about subgroup types and actually could include these extensions.

So for now, I favor Edward’s current solution.  I bet you wouldn’t be able to break it even with a very aggressive attack.  For later, I like the idea of eventually extending the system with subgroup configuration data, and at the same time we could move to your proposed stronger solution, even further reducing the risk of a failed restart (one that would leave the system in need of manual “repair”, actually).

**Comment by mpmilano** [comment]
The solution Edward outlined is going to take priority here. The management subgroup will not be pursued for this.
