### ISSUE TITLE
Make the version number meaningful.

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho-unified#80]
The current version number of a persistent variable is a combination of the message sequence number and the view id. Before we have the null message mechanism, it's easy to match the version number and its corresponding messages due to the strict round robin order. Once the null messages are enabled, we cannot do that anymore. In the persistent callback, the application, like the object store, can not figure out which message has been persisted from the version number.

We need a token for each of the ordered_send. One option is to use the version as the token ID, but we need to wait until delivery. This can be done by returning a future.

Or we can pass the version number in the stability callback (this is disabled for cooked send...does it hurt things by enabling it in `MulticastGroup::deliver_message()`?), where the application connects the version to the corresponding message. 

What do you think?

**Comment by KenBirman** [comment]
I think the version number should be available when the delivery event handler runs (I would probably just add a built-in method persistent<t>::getversionnumber() or v::getversionnumber() to the versioning library, since these numbers are only used to index version vectors).  Then I would make it an additional optional argument to the stability upcall.
